# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(max_length=201),
        ),
    ]
