# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190423_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='ans1',
            field=models.CharField(default='Nothing', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='ans2',
            field=models.CharField(default='Nothing', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='ans3',
            field=models.CharField(default='Nothing', max_length=200),
            preserve_default=False,
        ),
    ]
