# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190425_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='ans1',
            new_name='answer1',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='ans2',
            new_name='answer2',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='ans3',
            new_name='answer3',
        ),
    ]
