# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190425_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='poll',
            field=models.CharField(max_length=200),
        ),
    ]
